# Reference: https://github.com/repository-settings/app

_extends: .github

repository:
  name: platform-mon-storefront
  description: Launch a branded data storefront
  topics: web, monetization
  private: false
  has_issues: true
  has_projects: true
  has_discussions: false

teams:
  - name: sysadmin
    permission: admin
  - name: engineering
    permission: push
  - name: product
    permission: triage
  - name: frontend
    permission: push

environments:
  - name: production

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - CodeQL

milestones:
  - title: 0.0.2
    description: DRAFT
    state: open
