AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Storefront static hosting

Parameters:
  HostedZone:
    Type: String
    Description: Hosted zone ID for the domain

Resources: