Domain:
  Type: AWS::Route53::RecordSet
  Properties:
    HostedZoneId: !Ref HostedZone
    Name: storefront.tiki.company
    Type: CNAME
    TTL: 300
    ResourceRecords:
      - !GetAtt CloudFrontDistribution.DomainName